### ISSUE TITLE
Issue with crontab

### ISSUE THREAD

**Issue by thoventive** [CaseyLabs/aws-ec2-ebs-automatic-snapshot-bash#10]
Hi, 

I have tested the script with command (sudo /opt/aws/ebs-snapshot.sh) and it works. But when I setup a crontab look like below in an AWS EC2 (AMI Linux)

*/1 * * * root  AWS_CONFIG_FILE="/root/.aws/config" /opt/aws/ebs-snapshot.sh

No snapshot was created each minute.

Would you please help me fix the issue with this crontab?

**Comment by thoventive** [comment]
I found the correct one is

AWS_CONFIG_FILE="/root/.aws/config"
*/1 * * * sudo /opt/aws/ebs-snapshot.sh

**Comment by CaseyLabs** [comment]
I've updated the install instructions to include this version of a crontab job.
