### ISSUE TITLE
How to setup the crontab within a docker container

### ISSUE THREAD

**Issue by kentmw** [CaseyLabs/aws-ec2-ebs-automatic-snapshot-bash#16]
I was wondering how to get this script to run whilst in a docker container. This is currently what I have:
Dockerfile:
```
FROM    phusion/baseimage:0.9.16

# Installation:
RUN apt-get update
... install app

COPY ebs-snapshot.sh /other/ebs-snapshot.sh
ADD docker-start.sh /other/

RUN chmod +x /other/docker-start.sh

CMD ./other/docker-start.sh
```
docker-start.sh:
```
if [ "$EBS" = "backup" ]; then
  echo "Setting up ebs backup";
  chmod +x ebs-snapshot.sh
  # setup cron
  ( crontab -l 2>/dev/null | grep -Fv ebs-snapshot ; printf -- "55 22 * * *  AWS_CONFIG_FILE=\"/root/.aws/config\" /other/ebs-snapshot.sh\n" ) | crontab
fi
```

Yet it does not fire nightly. I can, however, create a snapshot if I bash into the docker container and manually call ebs-snapshot.sh

**Comment by CaseyLabs** [comment]
Hi Kent,

Have a look at this pull request: https://github.com/CaseyLabs/aws-ec2-ebs-automatic-snapshot-bash/pull/14

You may need to add the "exit 0" to the end of the script for Docker. I'm hoping to merge in this pull request into the main repo shortly to make the script more Docker friendly.

If this doesn't solve the issue, let me know and I'll help debug.

Cheers,

Sean

**Comment by kentmw** [comment]
Thanks for the quick response. I'll test and get back to you shortly

**Comment by kentmw** [comment]
I added the exit 0 to the script, and it still wasn't working. But I managed to get it working after playing around with the cron job and setting up a log file
```
( crontab -l 2>/dev/null | grep -Fv ebs-snapshot ; printf -- "55 23 * * * AWS_CONFIG_FILE=\"/root/.aws/config\" /other/ebs-snapshot.sh >> /var/log/cron.log 2>&1\n" ) | crontab
```

Not sure what exactly fixed it though.
