### ISSUE TITLE
Change description and/or tag from Config file

### ISSUE THREAD

**Issue by VoodooPrawn** [CaseyLabs/aws-ec2-ebs-automatic-snapshot-bash#19]
Firstly, this is amazing, I use it on all my EC2s, so a huge thank you for making this open to everyone.

I've had it running for a while, but on my AWS there are about 20 EC2s running it, so as you can imagine, lots of snaps! Would it be easy/possible to make the Description and/or Tag overwritable, the default is ok, but not always easy to tie to a specific client (each client has their own EC2 in my set up).

If in the config there was a setting that you could put in a string, so my snaps could all be named by client (then the date is obviously visible on AWS Console anyway)

If I had any experience with shell scripts I'd happily add this in... but I don't at all (filthy PHP developer unfortunately haha).

Thanks again for this wonderful tool!

**Comment by VenkataMutyala** [comment]
Have you tried tweaking line 79 in the script?

**Comment by VoodooPrawn** [comment]
Nope, but just had a look and that looks like the exact bit that could be tweaked. Thanks. :)
