### ISSUE TITLE
credentials not found

### ISSUE THREAD

**Issue by vindude5** [CaseyLabs/aws-ec2-ebs-automatic-snapshot-bash#20]
Hi 
I am trying to use your script but i am facing issue with credentials.
It is not able to find credentials. Attached screenshot.

AWS CLI is installed. Attached screenshot.
How can I overcome this issue.?

![cli 2](https://cloud.githubusercontent.com/assets/19265361/15112585/cf487fa4-160c-11e6-92b2-c30d359ec20a.PNG)
![cli](https://cloud.githubusercontent.com/assets/19265361/15112586/cf4e46e6-160c-11e6-9881-6753c0742c60.PNG)

**Comment by CaseyLabs** [comment]
Unfortunately, this is an issue with your AWS CLI configuration, not with the script. If you are using IAM credentials and not an IAM role, you'll need to re-run the "aws configure" command and enter in the appropriate credentials.
