### ISSUE TITLE
Script is not working in Ubuntu

### ISSUE THREAD

**Issue by gugan-mohan** [CaseyLabs/aws-ec2-ebs-automatic-snapshot-bash#4]
When I follow the steps which you explained here is not working in ubuntu machine.
Here is the error I am getting while running it.

ebs-snapshot.sh: 5: set: Illegal option -o pipefail

Please Help me to solve this issue.

Thanks
Emkay

**Comment by CaseyLabs** [comment]
Hi there,

I haven't run into this issue before unfortunately. Which version of Ubuntu are you using (and which AMI id)?

What happens when you run this command as root:
```
set -o pipefail
```

**Comment by gugan-mohan** [comment]
I really apologize for opening this ticket. I were executing the script using sh ebs-snapshot.sh command and I got above error, And when I tried command bash ebs-snapshot.sh.  It is working fine now. Once again sorry for this ticket.

Thanks for your immediate response on this task.   

Thanks
Emkay
